### PR TITLE
Add Travis & Codeclimate Badges

### PR DESCRIPTION
**Pull request by abookyun**
As title. :)

### CODE REVIEW

**Comment by amatsuda** [comment]
@abookyun Thanks, but why do you think we need those badges?

**Comment by abookyun** [comment]
IMHO, because it's a way to tell people the project was coded well and tested well. At least, I think it looks beautiful in README.

**Comment by amatsuda** [comment]
Good reasons. Thanks :)

**Comment by abookyun** [comment]
Nice! thanks!

**Pull request merged**
