### PR TITLE
Remove duplicated `delete_all`

### PR DESCRIPTION
**Pull request by yui-knk**
We `delete_all` all models in "spec_helper.rb"'s before block.

### CODE REVIEW

**Comment by amatsuda** [comment]
What do you mean by "deprecated" delete_all?
Duplicated?

**Comment by yui-knk** [comment]
:tired_face:  Yes "Duplicated"

**Comment by yui-knk** [comment]
Can I `git commit --amend` and `push -f`  ?

**Comment by amatsuda** [comment]
Sure, of course!

**Comment by yui-knk** [comment]
Update commit title and PR title to "duplicated".

**Comment by amatsuda** [comment]
:grin:

**Pull request merged**
