### PR TITLE
Support Rails 6.1

### PR DESCRIPTION
**Pull request by y-yagi**
`PartialRenderer` was refactored by rails/rails#38594 This fixes to follow to new render behavior.

Also, updated tests for `partial`. Because objects of original tests were decorated via `RelationDecorator#records` and didn't affected by `PartialRenderer` monkey.

### CODE REVIEW

**Comment by jamesbrooks** [comment]
Thanks for this @y-yagi. This resolves the issue I was having in Rails 6.1 using `ApplicationController.renderer.render`. This PR fixes #112.

Can we please get this merged in soon @amatsuda, thanks!

**Comment by amatsuda** [comment]
@y-yagi Hi! Glad seeing you here, and thank you so much for the perfectly crafted patch! ❤️

**Comment by amatsuda** [comment]
@y-yagi @jamesbrooks Published a new gem package versioned 1.3.4 with this patch. Thanks!

**Comment by jamesbrooks** [comment]
Awesome, thank you @amatsuda!

**Pull request merged**
