### PR TITLE
Decorate associated objects

### PR DESCRIPTION
**Pull request by itkrt2y**
Decorate associations(`ActiveRecord::Associations::Association#target`) when `ActiveRecord::Associations::Association#owner` has passed through `ActiveDecorator::Decorator#decorate`.
`owner` is decorated by current logic, so with this change, associated objects come to be decorated in view context.

### CODE REVIEW

**Comment by vendethiel** [comment]
like #8?

**Comment by itkrt2y** [comment]
@vendethiel Yes!

But this PR is more efficient than #8.
#8 decorates all associations after decorating objects, so It is too wasteful.
This PR decorates only called associations, so very efficient!

**Comment by amatsuda** [comment]
@itkrt2y Thank you for updating the code and keeping the PR fresh.
The code looks way better than the initial version now, but I want you to make some more improvements for this PR to get merged.

Firstly, please squash your "Refactoring" commit to the first one. We don't need that history in master.

Secondly, you're trying to do too much things in one commit. In this case,
* `decorate` used not to return the decorated object when then given object was already decorated. This patch changes that behavior without explaining it anywhere, nor adding tests.
* You added a new feature to automatically decorate already decorated AR model's associations, which is the main point of this PR

These two are separate concerns, and so should be done in separate commits. Since there had been two PRs (#15, #59) addressing the first one with tests, I just merged #15.
Can you rebase again so that your changeset would include only one feature?

Thirdly, do you think you can add some more tests to make sure how it works (or does not work) with other types of AR associations such as `has_one`, `belongs_to`, and `has_many :through`?

**Comment by itkrt2y** [comment]
@amatsuda I rebased and added tests that covers all AR Association types 👍

**Comment by amatsuda** [comment]
@itkrt2y Thank you so much! Well done so far!

However, this PR introduces another big implicit specification change, and a breakage due to that change.
The `decorate` method used to do nothing for objects for which ActiveDecorator couldn't find a corresponding decorator module.

But since the `decorate` method now tries to extend every object that are passed to templates, not only it may needlessly `extend` too many objects, it would cause errors with objects that cannot be extended, for example
* Integers
* Symbols
* frozen objects
* objects of which singleton_class is frozen

This can very easily be confirmed by adding something like this in the test controller:
```patch
diff --git a/test/fake_app/fake_app.rb b/test/fake_app/fake_app.rb
index b3da2a9..daf82f9 100644
--- a/test/fake_app/fake_app.rb
+++ b/test/fake_app/fake_app.rb
@@ -152,6 +152,7 @@ class ApplicationController < ActionController::Base
 end
 class AuthorsController < ApplicationController
   def index
+    @number = 1
     if Author.respond_to?(:scoped)
       # ActiveRecord 3.x
       if params[:variable_type] == 'array'
```

So again, please try not to make more than one change in one commit. And please don't change anything that are not described in the commit message.

**Comment by itkrt2y** [comment]
oh, I'm sorry😵 . I try to fix ASAP.

**Comment by itkrt2y** [comment]
Fixed 🏥

**Pull request merged**
