### PR TITLE
Decorate models where nil? returns true

### PR DESCRIPTION
**Pull request by jamesbrooks**
A model may implement or delegate `nil?` to check the value of an attribute rather than the object instance as a whole.

Action Text implemented `nil?` in this way and as a result decorating a model which has Action Text rich-text fields where those fields have empty contents will cause problems accessing the associated `ActionText::RichText` record after decoration.

e.g. https://github.com/rails/rails/blob/da5b1c3bb7041af03d5c24bce2639349f7fcb5c2/actiontext/app/models/action_text/rich_text.rb#L12

### CODE REVIEW

**Comment by chris-gooley** [comment]
+1

Worked for me. Is it possible to get this merged in

**Comment by jamesbrooks** [comment]
If anyone else impacted by this issue feel free to use my fork until this PR is merged in:

```ruby
# Gemfile
gem 'active_decorator', github: "jamesbrooks/active_decorator"
```

**Comment by jamesbrooks** [comment]
Bump. Is it possible to get this merged in soon?

**Comment by jamesbrooks** [comment]
@amatsuda would it be possible to have a look at this PR and consider merging it in soon, otherwise if there is a glaring issue with it I would be more then happy to make any changes you require - let me know! :) many thanks!

**Comment by jamesbrooks** [comment]
Freshly rebased against master :)

**Comment by Griffinstein** [comment]
Same issue using ActionText, this PR fixes it

**Comment by jamesbrooks** [comment]
@amatsuda is it possible to get this merged in, or if there are any issues with the PR or the general gist of it please let me know! Thanks a lot :)

**Comment by amatsuda** [comment]
@jamesbrooks Just merged this PR, and pushed a little bit of super trivial additions ( a795cea57753cca19b9695e1ec859d05275b2403 et al.), then published the version 1.4.0 gem.
Thank you for sending the patch, and patiently waiting!

**Comment by jamesbrooks** [comment]
@amatsuda thanks! those other cases seem completely reasonable to have also handled the same way, looks good :)

**Pull request merged**
